language: node_js

notifications:
  email:
    on_success: never
    on_failure: change

before_install:
  - nvm install $NODE

script:
  - npm run lint
  - npm run build
  - npm rm tslint
  - npm install $TYPESCRIPT --force
  - npm run test-cov

env:
  - NODE=6 TYPESCRIPT=typescript@latest
  - NODE=stable TYPESCRIPT=typescript@latest
  - NODE=stable TYPESCRIPT=typescript@2.0
  - NODE=stable TYPESCRIPT=typescript@next

node_js:
  - stable

after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
