language: node_js

notifications:
  email:
    on_success: never
    on_failure: change

script:
  - npm run build
  - npm run lint
  - npm rm tslint
  - npm install $TYPESCRIPT --force
  - npm run test-cov

env:
  - TYPESCRIPT=typescript@1.6
  - TYPESCRIPT=typescript@1.7
  - TYPESCRIPT=typescript@1.8
  - TYPESCRIPT=typescript@next

node_js:
  - "0.12"
  - "iojs"
  - "4"
  - "stable"

after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
