--- 
contact_links: 
  - 
    name: Question
    about: "Please ask and answer usage questions in our Discussion forum."
    url: "https://github.com/TypeStrong/ts-node/discussions"
  - 
    name: Chat
    about: "Alternatively, you can use the TypeScript Community Discord."
    url: "https://discord.gg/typescript"
  - 
    name: "Help! My Types Are Missing!"
    about: "This is likely a configuration problem.  Check our README"
    url: "https://github.com/TypeStrong/ts-node/blob/master/README.md#help-my-types-are-missing"
  - 
    name: "TSError or SyntaxError"
    about: "These errors come from TypeScript and node, respectively.  Use StackOverflow or Discord for usage and configuration help."
    url: "https://stackoverflow.com/questions/tagged/ts-node"
